services:
  osint-sherlock:
    image: ghcr.io/arisecrewyes/osint:latest
    container_name: osint-sherlock
    restart: unless-stopped
    expose:
      - "9090"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - root_default

networks:
  root_default:
    external: true
