services:
  osint-sherlock:
    image: ghcr.io/arisecrewyes/osint:latest
    container_name: osint-sherlock
    restart: unless-stopped
    expose:
      - "9090"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - root_default

  osint-gitrecon:
    image: ghcr.io/arisecrewyes/gitrecon:latest
    container_name: osint-gitrecon
    restart: unless-stopped
    expose:
      - "9091"
    networks:
      - root_default

  osint-google-dorking:
    image: ghcr.io/arisecrewyes/google-dorking:latest
    container_name: osint-google-dorking
    restart: unless-stopped
    expose:
      - "9092"
    networks:
      - root_default

networks:
  root_default:
    external: true
